apiVersion: v1
kind: Service
metadata:
  labels:
    app: kong
  name: kong
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: admin-api
    nodePort: 31876
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: api
    nodePort: 31875
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kong
  sessionAffinity: None
  type: LoadBalancer
