---
- hosts: local
  vars:
    api_list: []
    opa_policies: []

    kong_apis:
    - name: createContent
      uris: "/content/v1/create"
      upstream_url: "http://knowledge-mw:5000/v1/content/create"
      checks: [
      {
          "type": "roleCheck",
          "tokenKey": "CONTENT_CREATOR"
      },
      {
          "type": "orgCheck",
          "bodyKey": "request.content.createdFor[*]"
      },
      {
          "type": "ownerCheck",
          "headerKey": "request.userId"
      }]

    - name: createCourse
      uris: "/content/v1/create"
      upstream_url: "http://knowledge-mw:5000/v1/course/create"
      checks: [
      {
          "type": "roleCheck",
          "tokenKey": "COURSE_CREATOR"
      },
      {
          "type": "orgCheck",
          "bodyKey": "request.content.createdFor[*]"
      },
      {
          "type": "ownerCheck",
          "headerKey": "request.userId"
      }]

    - name: createBook
      uris: "/content/v1/create"
      upstream_url: "http://knowledge-mw:5000/v1/user/create"
      checks: [
      {
          "type": "roleCheck",
          "tokenKey": "BOOK_CREATOR"
      },
      {
          "type": "orgCheck",
          "bodyKey": "request.content.createdFor[*]"
      },
      {
          "type": "ownerCheck",
          "headerKey": "request.userId"
      }]

  tasks:
  - set_fact:
      api_list: "{{ api_list + [item | dict2items | rejectattr('key', 'equalto', 'roleCheck') | rejectattr('key', 'equalto', 'orgCheck') | rejectattr('key', 'equalto', 'ownerCheck') | list | items2dict] }}"
      opa_policies: "{{ opa_policies + [item | dict2items | rejectattr('key', 'equalto', 'uris') | rejectattr('key', 'equalto', 'strip_uri') | rejectattr('key', 'equalto', 'plugins') | list | items2dict] }}"
    with_items:
      - "{{ kong_apis }}"
#  - debug: msg={{ api_list }}
#  - debug: msg="{{ opa_policies[0].name }}"
#  - copy: dest=/tmp/opa_policies.json content="{{ opa_policies | to_nice_json}}"
#  - copy: dest=/tmp/kong_apis.json content="{{ api_list | to_nice_json}}"
#  - debug: "{{ item }}"
#    with_items:
#    - "{{ test_dict }}"
  - template:
      src: opa-policies.rego.j2
      dest: opa-policies.rego

  - shell: cat opa-policies.rego
