apiVersion: v1
kind: Service
metadata:
  labels:
    app: headerecho
  name: headerecho
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31077
    port: 4002
    protocol: TCP
    targetPort: 4000
  selector:
    app: headerecho
  sessionAffinity: None
  type: LoadBalancer
