apiVersion: v1
kind: Service
metadata:
  labels:
    app: headerecho-kong
  name: headerecho-kong
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32111
    port: 8002
    protocol: TCP
    targetPort: 8000
  selector:
    app: headerecho-kong
  sessionAffinity: None
  type: LoadBalancer
