apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-20T15:58:09Z"
  labels:
    app: content
  name: content
  namespace: default
  resourceVersion: "19122"
  selfLink: /api/v1/namespaces/default/services/content
  uid: 9b35fdf8-98b3-4594-b5c5-82e21e884e66
spec:
  clusterIP: 10.43.228.156
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31085
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: content
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.19.0.2
